gsitemap.php

Little fix in the XML formating.

[-] : additionnal line breaks 

---

gsitemap.php

Line 510: Image link for manufacturers in sitemap files with http even if https in enabled
Line 861: Sitemap links in sitemap index file with http even if https in enabled

[-] MO :  Bad protocol in ssl

---

gsitemap-cron.php
gsitemap.php

Converted private functions and vars to protected to allow override

[*] MO: allow override

---

gsitemap.php

http://forge.prestashop.com/browse/NM-409

[-] MO : Product visibility taken into account in gsitemap

---

gsitemap-cron.php

Remove function p, it does not exist anymore

Update gsitemap-cron.php - Remove function p()

---

views/templates/admin/configuration.tpl

"Informations" -> "Information"

Fix typo in wording

---

gsitemap.php

Apply CS fixer

---

gsitemap.php

Fixes: https://github.com/PrestaShop/gsitemap/issues/58

Fix wrong use of protocol

---

gsitemap.php

Fixes: https://github.com/PrestaShop/gsitemap/issues/59

Remove the home category from the sitemap

---

gsitemap.php

Reverts PrestaShop/gsitemap#68

Revert "Use meta description instead of description"

---

gsitemap.php

Rebuild #68 because it was merge on master instead of dev.
Already QA approved.

Use meta description instead of description

---

gsitemap-cron.php

Do not call getIsset() with getValue()

---

gsitemap.php

Fix failure when generating sitemap with >25000 links

---

views/templates/admin/configuration.tpl

| Description?  | Fixed the display & behavior for "Uncheck/Check All" button
| Type?         | bug fix
| Fixed ticket? | Fixes PrestaShop/Prestashop#18603
| How to test?  | Cf PrestaShop/Prestashop#18603

Fixed the display & behavior for "Uncheck/Check All" button

---

gsitemap-cron.php
gsitemap.php
index.php
translations/index.php
upgrade/index.php
upgrade/install-2.2.php
views/img/index.php
views/index.php
views/templates/admin/configuration.tpl
views/templates/admin/index.php
views/templates/index.php

Fix outdated license headers
This PR is created automatically by [Matks PrestaShop Repositories Bulk Editor](https://github.com/matks/prestashop-repos-bulk-editor)

Fix outdated license headers

---

composer.json
composer.lock

| Description?  | Add prepend-autoloader: false in composer.json
| Type?         | improvement
| Deprecations |  no
| How to test?  | No need for QA

Add prepend-autoloader: false in composer.json

---

gsitemap-cron.php
gsitemap.php
index.php
translations/index.php
upgrade/index.php
upgrade/install-2.2.php
views/img/index.php
views/index.php
views/templates/admin/configuration.tpl
views/templates/admin/index.php
views/templates/index.php

Fix (again) license headers
This PR is created automatically by [Matks PrestaShop Repositories Bulk Editor](https://github.com/matks/prestashop-repos-bulk-editor)

Fix license headers - part 2

---

gsitemap.php

| Description?  | Set tab property.
| Type?         | bug fix
| Fixed ticket? | Fixes PrestaShop/Prestashop#27075.

Set property tab

---

gsitemap.php

message: PHP Notice:  Trying to access array offset on value of type bool in /www/modules/gsitemap/gsitemap.php on line 419PHP
start at PHP 7.4

Fixed PHP Notice: Trying to access array offset on value of type bool in /www/modules/gsitemap/gsitemap.php on line 419

---

config.xml
gsitemap.php

| Description?  | Bump version to 4.2.1
| Type?         | improvement
| Fixed ticket? | N/A
| How to test?  | N/A

Bump version to 4.2.1

---

README.md
gsitemap.php

| Description?  | Fix wording
| Type?         | improvement
| Fixed ticket? | Fixes PrestaShop/PrestaShop#{31935
| How to test?  |

Fix wording

---

README.md

| Description?  | Replace old urls
| Type?         | refacto
| Fixed ticket? | N/A
| How to test?  | N/A

Replace old urls

---

config.xml
gsitemap.php

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Bump module version number.
| Type?             | 
| BC breaks?        | 
| Deprecations?     | 
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |

Bump version number to 4.4.1
